title: Palette
context:
    text: This is an example component!
    variation: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]
    liste: ["red", "pink", "purple", "deep-purple", "indigo", "blue", "light-blue", "cyan", "teal", "green", "light-green", "lime", "yellow", "amber", "orange", "deep-orange", "brown", "grey", "blue-grey"]